# Generated by Django 5.0.14 on 2025-08-09 18:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('PE', 'Pendiente'), ('EP', 'En progreso'), ('CO', 'Completado'), ('CA', 'Cancelado')], default='PE', max_length=2)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Orden de trabajo',
                'verbose_name_plural': 'Órdenes de trabajo',
                'ordering': ['-fecha_creacion', '-id'],
            },
        ),
    ]
