# Generated by Django 5.0.14 on 2025-08-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ot', '0001_initial'),
        ('otservicio', '0001_initial'),
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ot',
            name='servicios',
            field=models.ManyToManyField(blank=True, related_name='ots', through='otservicio.OTServicio', to='servicio.servicio'),
        ),
    ]
