# Generated by Django 5.0.14 on 2025-08-09 18:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ot', '0002_initial'),
        ('otusuario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ot',
            name='usuarios',
            field=models.ManyToManyField(blank=True, related_name='ots', through='otusuario.OTUsuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='ot',
            index=models.Index(fields=['estado'], name='ot_ot_estado_9deb37_idx'),
        ),
        migrations.AddIndex(
            model_name='ot',
            index=models.Index(fields=['fecha_inicio', 'fecha_finalizacion'], name='ot_ot_fecha_i_549201_idx'),
        ),
        migrations.AddIndex(
            model_name='ot',
            index=models.Index(fields=['titulo'], name='ot_ot_titulo_8849c8_idx'),
        ),
    ]
