# Generated by Django 5.0.14 on 2025-08-09 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ot', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ot_usuarios', to='ot.ot')),
            ],
        ),
    ]
