# Generated by Django 5.0.14 on 2025-08-09 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otusuario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='otusuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ot_usuarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='otusuario',
            index=models.Index(fields=['ot'], name='otusuario_o_ot_id_61caaa_idx'),
        ),
        migrations.AddIndex(
            model_name='otusuario',
            index=models.Index(fields=['usuario'], name='otusuario_o_usuario_8394d3_idx'),
        ),
        migrations.AddIndex(
            model_name='otusuario',
            index=models.Index(fields=['ot', 'usuario'], name='otusuario_o_ot_id_682737_idx'),
        ),
        migrations.AddConstraint(
            model_name='otusuario',
            constraint=models.UniqueConstraint(fields=('ot', 'usuario'), name='uq_ot_usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='otusuario',
            unique_together={('ot', 'usuario')},
        ),
    ]
