# Generated by Django 5.0.14 on 2025-08-11 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('empleado', 'Empleado'), ('inventario', 'Inventario'), ('user', 'Usuario Regular')], max_length=20),
        ),
    ]
