# Generated by Django 5.0.14 on 2025-08-09 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ot', '0001_initial'),
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ot_servicios', to='ot.ot')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ot_servicios', to='servicio.servicio')),
            ],
            options={
                'indexes': [models.Index(fields=['ot'], name='otservicio__ot_id_7099b7_idx'), models.Index(fields=['servicio'], name='otservicio__servici_04d73e_idx'), models.Index(fields=['ot', 'servicio'], name='otservicio__ot_id_7ce217_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='otservicio',
            constraint=models.UniqueConstraint(fields=('ot', 'servicio'), name='uq_ot_servicio'),
        ),
        migrations.AlterUniqueTogether(
            name='otservicio',
            unique_together={('ot', 'servicio')},
        ),
    ]
