# Generated by Django 5.0.14 on 2025-08-09 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insumo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsumoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('notas', models.TextField(blank=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicio_items', to='insumo.insumo')),
            ],
            options={
                'verbose_name': 'Insumo – Servicio',
                'verbose_name_plural': 'Insumos – Servicio',
            },
        ),
    ]
