# Generated by Django 5.0.14 on 2025-08-09 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insumoservicio', '0001_initial'),
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumoservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumo_items', to='servicio.servicio'),
        ),
        migrations.AddIndex(
            model_name='insumoservicio',
            index=models.Index(fields=['servicio'], name='insumoservi_servici_77d307_idx'),
        ),
        migrations.AddIndex(
            model_name='insumoservicio',
            index=models.Index(fields=['insumo'], name='insumoservi_insumo__4da22b_idx'),
        ),
        migrations.AddIndex(
            model_name='insumoservicio',
            index=models.Index(fields=['servicio', 'insumo'], name='insumoservi_servici_7e1dc0_idx'),
        ),
        migrations.AddConstraint(
            model_name='insumoservicio',
            constraint=models.UniqueConstraint(fields=('servicio', 'insumo'), name='uq_servicio_insumo'),
        ),
        migrations.AlterUniqueTogether(
            name='insumoservicio',
            unique_together={('servicio', 'insumo')},
        ),
    ]
