# Generated by Django 5.0.14 on 2025-08-09 18:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insumo', '0001_initial'),
        ('insumoservicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('PE', 'Pendiente'), ('EP', 'En progreso'), ('CO', 'Completado'), ('CA', 'Cancelado')], default='PE', max_length=2)),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('insumos', models.ManyToManyField(blank=True, related_name='servicios', through='insumoservicio.InsumoServicio', to='insumo.insumo')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['estado'], name='servicio_se_estado_c7d789_idx'), models.Index(fields=['nombre'], name='servicio_se_nombre_83c8ef_idx')],
            },
        ),
    ]
